name: CI/CD

on: [push]

jobs:
  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      AWS_DEFAULT_REGION: "us-east-2"
      AWS_ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.SECRET_KEY }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Create ZIP for Lambda
      run: |
        rm -rf modules/lambda/app/lambda.zip 2> /dev/null && zip -r9 modules/lambda/app/lambda.zip modules/lambda/app/*
    - uses: actions/download-artifact@master
    - name: Terraform Init
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'init'
        tf_actions_comment: false
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'apply'
        tf_actions_comment: false
        args: '-var-file="vars.tfvars"'
    - name: Terraform Output
      id: terraform
      uses: hashicorp/terraform-github-actions@master
      with:
        tf_actions_version: 0.12.13
        tf_actions_subcommand: 'output'
        tf_actions_comment: false
        args: 'url'
    - name: Show Output  
      run: echo ${{ steps.terraform.outputs.tf_actions_output }}